### PR TITLE
Ability to evaluate defense positions for multiple races

### PR DESCRIPTION
**Pull request by kant2002**
This is two-fold change, first one is to simplify testing, and
don't require setting up Broodwar variable which is cumbersome.
Also I want to maintain compatibility with existing codebase as much as possible.
Also bot now could theoretically evaluate defenses of enemy as well.
If this is now not possible, at least this is step in that direction.

One of the proposed changes related to #11

### CODE REVIEW

**Comment by kant2002** [comment]
@Cmccrave please take a look

**Comment by Cmccrave** [comment]
Is this goal of this to be able to generate blocks for all 3 races for testing purposes?

**Comment by Cmccrave** [comment]
I think this could be useful if wanting to differentiate blocks into race specific (@NiteKat does some team melee stuff with tri race), so this could be useful in the future when dynamic addition is considered. Thanks.

**Comment by kant2002** [comment]
My intentions was following.
- `methodName()` is for simple and quick implementations and for backward compatibility.
- `methodName(race)` is for testing and if somebody would be so brave to support bot with mixed race
- `methodName(player)` to support bots which willing to project defenses of their enemies. I’m not sure is this needed, but I think this could be just convenience method. It is debatable should it go to public surface or not. At least willing to hear opinions on this

**Pull request merged**
