### PR TITLE
Remove measurements from the code

### PR DESCRIPTION
**Pull request by kant2002**
The measurements done in such way, that it could be
easily done outside of the library code. The actual output to Brodwar variable
make code depends on the BWAPI which complicated testing and possible
porting to other games, for example for SC2. If you want to
have time measurements as part of library, I propose have separate methods
which indicate on measurement to be done.
For example `findBlocksWithTiming` would be used in code, but main code which
do the work will be dependency free.

This is one of proposal to https://github.com/Cmccrave/BWEB/issues/11

### CODE REVIEW

**Comment by N00byEdge** [comment]
`Wall.cpp` has not had its `#include <chrono>` removed. We should have that for completeness sake.

**Review by N00byEdge — DISMISSED** [review]
`Wall.cpp` has not had its `#include <chrono>` removed. We should have that for completeness sake.

**Comment by N00byEdge** [comment]
Nice. Does this build? I feel like we need a testing system.

**Comment by kant2002** [comment]
I'm all-in for having that library compile in Travis or something like this.

**Pull request merged**
